[package]
name = "rust-101"
version = "0.1.1"
author = ["Maurizio La Rocca <mrz.larocca@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
